name: Deploy

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run tests
    env:
      TESTING: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.4'

      - name: Setup Python Virtual Environment
        run: python -m venv python3-virtualenv

      - name: Install Dependencies
        run: python3-virtualenv/bin/pip install -r requirements.txt

      #- name: Run Tests
      #  run: ./run_test.sh

  deploy:
    name: "Deploy SQLite App to VPS"
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Install SSHPass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy SQLite App
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@$SSH_IP <<'EOF'
          set -e
          cd ${{ secrets.PROJECT_ROOT }}
          git pull origin main
          docker-compose -f docker-compose.dev.yml down
          docker-compose -f docker-compose.dev.yml up -d --build
          EOF
        env:
          SSH_IP: ${{ secrets.SSH_IP }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          PROJECT_ROOT: ${{ secrets.PROJECT_ROOT }}

        #- name: Send Failure Message to Discord
        #  if: failure()
        #  run: |
        #    curl -s -X POST "${{ secrets.DISCORD_WEBHOOK }}" -d "content=🚨 Deployment Failed for SQLite App"

      - name: Print Container Status
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@$SSH_IP 'cd ${{ secrets.PROJECT_ROOT }} && docker-compose -f docker-compose.prod.yml ps'

      #- name: Deployment Successful Message
      #  run: |
      #    curl -s -X POST "${{ secrets.DISCORD_WEBHOOK }}" -d "content=🚀 Deployment Successful for SQLite App"
